#!/usr/bin/env python3
# Inspired by:
# * https://stackoverflow.com/a/46669656
# * https://github.com/user-none/Bin-Headers
# Usage ./bin2header_struct.py --help

import argparse
import sys
import os

BYTES_PER_BUFFER = 4095 # C99 string literal limit.
BYTES_PER_LINE = 21

def stringify_nibble(nibble):
    if nibble < 10:
        return chr(nibble + ord('0'))
    return chr(nibble - 10 + ord('a'))

def write_byte(of, byte):
    of.write('\\x')
    of.write(stringify_nibble(byte >> 4))
    of.write(stringify_nibble(byte & 0xf))

def bin2header(infile, outfile, var_name):

    infile.seek(0, os.SEEK_END)
    file_size_bytes = infile.tell()
    infile.seek(0)

    outfile.write('/* AUTOGENERATED FILE - DO NOT EDIT */\n');
    outfile.write('#include <stddef.h>\n')
    outfile.write('\n')
    outfile.write('#ifndef EMBEDDED_BIN__{}\n'.format(var_name))
    outfile.write('#define EMBEDDED_BIN__{}\n'.format(var_name))
    outfile.write('extern const char *{};\n'.format(var_name));
    outfile.write('extern const size_t {}_len;\n'.format(var_name));
    outfile.write('#endif\n')
    outfile.write('\n')
    outfile.write('#ifdef EMBEDDED_BIN_IMPLEMENTATION__{}\n'.format(var_name))
    outfile.write('const struct {\n')

    # Struct definition.

    i = 0
    while file_size_bytes > 0:
        outfile.write('char s{}[{}] __attribute__ ((nonstring));\n'.format(i,
                        min(file_size_bytes, BYTES_PER_BUFFER)))
        file_size_bytes -= BYTES_PER_BUFFER
        i += 1

    outfile.write('}} {}_struct = {{\n'.format(var_name))

    # Hex dump.

    i = 0; j = 0
    while True:
        byte = infile.read(1)

        if byte == b"":
            # Place final " and break.
            if (i != 0 and j != 0):
                outfile.write('"\n')
            break

        if (j == 0):
            # Start of new line.
            outfile.write('"')

        write_byte(outfile, ord(byte))
        i += 1; j += 1

        if (i >= BYTES_PER_BUFFER):
            # Start of new buffer.
            i = 0; j = 0
            outfile.write('",\n')

        elif (j >= BYTES_PER_LINE):
            # End of line.
            j = 0
            outfile.write('"\n')


    outfile.write('};\n')
    outfile.write('const size_t {}_len = sizeof({}_struct);\n'.format(
                    var_name, var_name))
    outfile.write('const char *{} = (char*)(&{}_struct);\n'.format(
                    var_name, var_name));
    outfile.write('#endif\n')

def main():
    parser = argparse.ArgumentParser(
        description='Generate binary header output')
    parser.add_argument('-i', '--input', required=True, help='Input file')
    parser.add_argument('-o', '--out', required=True, help='Output file')
    parser.add_argument('-v', '--var', required=True,
                        help='Variable name to use infile file')

    args = parser.parse_args()
    if not args:
        return 1

    with open(args.input, 'rb') as infile:
        with open(args.out, 'w') as outfile:
            bin2header(infile, outfile, args.var)

    return 0

if __name__ == '__main__':
    sys.exit(main())
